Include rspec-rails in the test group, to try to fix a Travis-CI error.
The error:

```
$ bundle exec rake
rake aborted!
LoadError: cannot load such file -- rspec/core/rake_task
/home/travis/build/deseretbook/spree_address_book/Rakefile:4:in `require'
/home/travis/build/deseretbook/spree_address_book/Rakefile:4:in `<top (required)>'
```